# name: Continous Integration

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
  
#   client-build:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]
#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v4
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#         cache-dependency-path: './client/package-lock.json'
    
#     - name: "Install Client Dependencies"
#       run: npm install
#       working-directory: ./client

#     - name: "Build Client"
#       run: npm run build
#       working-directory: ./client

  
#   unit-test:
#     runs-on: ubuntu-latest
#     strategy:
#       matrix:
#         node-version: [18.x, 20.x, 22.x]
#     steps:
#     - uses: actions/checkout@v4
#     - name: Use Node.js ${{ matrix.node-version }}
#       uses: actions/setup-node@v4
#       with:
#         node-version: ${{ matrix.node-version }}
#         cache: 'npm'
#         cache-dependency-path: './client/package-lock.json'

#     - name: "Install Client Dependencies"
#       run: npm install
#       working-directory: ./client

#     - name: "Run Vitest"
#       run: npm run test
#       working-directory: ./client

